version: '3.9'

services:
  postgres_db:
    image: postgres:17.2
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_chats
    volumes:
      - postgres_data:/var/lib/postgresql/data

  node_server:
    build: .
    depends_on:
      - postgres_db
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres_db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root
      DATABASE_NAME: db_chats
    command: npm start
    volumes:
      - .:/app

volumes:
  postgres_data:
